#!/bin/sh
# export LC_ALL='C'
sed -r 's/<u>|<\/u>|\?//g' | tr '[A-Z]' '[a-z]' | tr '\`' "'" |\
    grep -e "<td[^>]*>" | sed -r 's/^\s*(<.*)$/\1/g' | \
    sed -r 's/<[^>]*>//g' | sed '/^$/d' | sed '0~2d' | \
    sed '1,2d' | sed 's/\s/\n/g' | sed '/^$/d' | \
    sed "/[^PKMNWLHAEIOUpkmnwlhaeiou\']/d" | sort -u
